export const ActionTypes = {
  FETCH_PRODUCTS: 'FETCH_PRODUCTS',
  SET_PRODUCTS: "SET_PRODUCTS",
  SET_CATEGORIES: "SET_CATEGORIES",
  SELECTED_PRODUCTS: "SELECTED_PRODUCTS",
  REMOVE_SELECTED_PRODUCTS: "REMOVE_SELECTED_PRODUCTS",
  GET_DATA: "GET_DATA",
  UPDATE_CART: "UPDATE_CART",
};
